## Tupla

In [ ]:
tupla = 13, 8.79, 'nombre'
print('tipo:', type(tupla), 'tamaño:', len(tupla), 'valores:', tupla)
print('posición 1 de la tupla:', tupla[1])

a, b, c = tupla  # desempaquetado
print('a =', a, 'b =', b, 'c =', c)

tipo: <class 'tuple'> tamaño: 3 valores: (13, 8.79, 'nombre')
pos 1: 8.79
a = 13 b = 8.79 c = nombre


In [ ]:
tupla2= (2, 25, 32)
print('tipo:', type(tupla2), 'tamaño:', len(tupla2), 'valores:', tupla2)
print('pos 1 de la tupla2:', tupla2[1])


a, b, c = tupla2  # desempaquetado
print('a =', a, 'b =', b, 'c =', c)

tipo: <class 'tuple'> tamaño: 3 valores: (2, 25, 32)
pos 1 de la tupla2: 25
a = 2 b = 25 c = 32


In [ ]:
tupladetupla= (tupla, tupla, (2,3,2))
print('tipo:', type(tupladetupla), 'tamaño:', len(tupladetupla), 'valores:', tupladetupla)
print('pos 1 de la tupla de tuplas:', tupladetupla[1])


a, b, c = tupladetupla  # desempaquetado
print('a =', a, 'b =', b, 'c =', c)

tipo: <class 'tuple'> tamaño: 3 valores: ((13, 8.79, 'nombre'), (13, 8.79, 'nombre'), (2, 3, 2))
pos 1 de la tupla de tuplas: (13, 8.79, 'nombre')
a = (13, 8.79, 'nombre') b = (13, 8.79, 'nombre') c = (2, 3, 2)


In [ ]:
tu= (1,2,2,3,5,2,5,6)
# En esta tupla guardamos la cantidad de hijos de un grupo de 8 personas, a continuación podremos contar con el método count, cuántos tienen 2 hijos.
tu.count(2)

3

## Listas


In [ ]:
lst_ent = [1, 2, 3, 4, 5]
lst_real = [1.0, 2.1, 4.8, 6.2]
lst_fecha = ["Martes", 29, 'de Enero', 2019]

In [ ]:
lst_uno = []
lst_dos = list()
print(lst_uno)
print('cantidad elementos en lista: ',len(lst_uno))

[]
cantidad elementos en lista:  0


### Generación automática con rangos

In [ ]:
gen = range(10)
gen

range(0, 10)

In [ ]:
list(gen)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### Agregando y removiendo elementos

In [ ]:
#Usando append
lst_uno.append("uno")

lst_uno

['uno']

In [ ]:
#Usando insert, requiere el índice
lst_uno.insert(1, "Batman")
lst_uno.insert(2, "Iron Man")
lst_uno.insert(3, "Capitán América")
lst_uno

['uno', 'Batman', 'Iron Man', 'Capitán América']

In [ ]:
#Usando pop para eliminar o remover
lst_uno.pop(0)
print(lst_uno)

['Batman', 'Iron Man', 'Capitán América']


In [ ]:
#Usando remove para eliminar de la lista el elemento que nombramos
lst_uno.remove("Batman")

In [ ]:
print(lst_uno)

['Iron Man', 'Capitán América']


### Agregar elementos a la lista y ordenarlos

In [ ]:
lst_dos.extend("Capitana Marvel")
print(lst_dos)

['C', 'a', 'p', 'i', 't', 'a', 'n', 'a', ' ', 'M', 'a', 'r', 'v', 'e', 'l']


In [ ]:
lst_uno =lst_uno + ["Thor", "Hulk"]
print(lst_uno)

['Iron Man', 'Capitán América', 'Thor', 'Hulk']


In [ ]:
a= [1,2,25,39,8,75,5,89,15,68]
a.sort()
a

[1, 2, 5, 8, 15, 25, 39, 68, 75, 89]

In [ ]:
lst_uno.sort(key=len)
lst_uno

['Thor', 'Hulk', 'Iron Man', 'Capitán América']

In [ ]:
valores = "32,45,11,87,20,48"
int_val =[]

for val in valores.split(","):
  int_valores = int(val)
  int_val.append(int_valores)

int_val 

[32, 45, 11, 87, 20, 48]

In [ ]:
int_val = [int(val) for val in valores.split(",")]
int_val

[32, 45, 11, 87, 20, 48]

## Conjuntos

In [ ]:
text3 = 'To be or not to be'
text4 = text3.split(' ')
print(text4)
print(len(text4))

w3 = set(text4)
print(w3)
print(len(w3))

w4 = set([word.lower() for word in text4])
print(w4)

['To', 'be', 'or', 'not', 'to', 'be']
6
{'be', 'To', 'to', 'or', 'not'}
5
{'to', 'or', 'be', 'not'}


In [ ]:
baloto= {21, 5, 12, 35, 22, 45, 45, 5}
baloto

{5, 12, 21, 22, 35, 45}

In [ ]:
set("reverse")

{'e', 'r', 's', 'v'}

In [ ]:
baloto.add(12)
baloto

{5, 12, 21, 22, 35, 45}

In [ ]:
#Operadores de conjuntos y pertenencia a conjuntos
print(1 in baloto, 5 in baloto)
revancha= {21, 25, 35, 39, 23}
print("Suma o unión: ", baloto | revancha, "Intersección o &: ", baloto.intersection(revancha), "Diferencia: ", baloto-revancha)

False True
Suma o unión:  {35, 5, 39, 12, 45, 21, 22, 23, 25} Intersección o &:  {35, 21} Diferencia:  {45, 12, 5, 22}


## Diccionarios

In [ ]:
edad = {'juan': 23, 'pablo': 60, 'zoe':16}
edad['july'] =  27   # agregar elemento
edad['soe']  =  33   # modfica un elemento
print('diccionario actual:', edad)

print(edad['pablo'])  # obtener una edad con la clave

del edad['juan'] # Borrar un elemento
edad['jose'] = 25 
print('diccionario actual:', edad)

print('Lista del diccionario', list(edad))

print('diccionario ordenado:', sorted(edad))

print('Buscar en el diccionario con in')
print('soe' in edad)
print('juan' in edad)
print('jorge' not in edad)

diccionario actual: {'juan': 23, 'pablo': 60, 'zoe': 16, 'july': 27, 'soe': 33}
60
diccionario actual: {'pablo': 60, 'zoe': 16, 'july': 27, 'soe': 33, 'jose': 25}
Lista del diccionario ['pablo', 'zoe', 'july', 'soe', 'jose']
diccionario ordenado: ['jose', 'july', 'pablo', 'soe', 'zoe']
Buscar en el diccionario con in
True
False
True


## JSON data

In [ ]:
import json

In [ ]:
## JSON data
obj = """
{"nombre": "Will",
"dondevive": ["USA", "España", "Colombia"],
"pet": null,
"hermanas": [{"nombre": "Silvia", "edad": 20, "mascotas": ["Trueno", "Zuko"] },
{"name": "Katie", "edad": 25, "mascotas": ["Zuko", "Cisco", "Tob"]}]
}
"""

In [ ]:
obj

'\n{"nombre": "Will",\n"dondevive": ["USA", "España", "Colombia"],\n"pet": null,\n"hermanas": [{"nombre": "Silvia", "edad": 20, "mascotas": ["Trueno", "Zuko"] },\n{"name": "Katie", "edad": 25, "mascotas": ["Zuko", "Cisco", "Tob"]}]\n}\n'

A) Solicitar al usuario que ingrese números, los cuales se guardarán en una lista. Finalizar al ingresar el número 0, el cual no debe guardarse.
B) A continuación, solicitar al usuario que ingrese un número y, si el número está en la lista, eliminar su primera ocurrencia. Mostrar un mensaje si no es posible eliminar.
C) Recorrer la lista para imprimir la sumatoria de todos los elementos.
D) Solicitar al usuario otro número y crear una lista con los elementos de la lista original que sean menores que el número dado. Imprimir esta nueva lista, iterando por ella.
E) Generar e imprimir una nueva lista que contenga como elementos a tuplas de dos elementos, cada una compuesta por un número de la lista original y la cantidad de veces que aparece en ella. Por ejemplo, si la lista original es [5,16,2,5,57,5,2] la nueva lista contendrá: [(5,3), (16,1), (2,2), (57,1)]

In [ ]:
#Crear lista vacía
lista =list()
#print(lista)
# A. Solicitar al usuario ingresar números
while not 0 in lista:
  lista.append(int(input("Ingrese un número para guardar en una lista, con 0 termina la lista (entero): ")))
#Eliminar de la lista el número 0
lista.remove(0)

print(lista)
#B. Eliminar el número de la lista, en su primera ocurrencia
eliminar= int(input("Ingrese un número para comprobar si está en la lista: "))
if eliminar in lista:
    lista.remove(eliminar)
else:
    print("Ese número no está entre los ingresados")

print(lista)

#C. Sumatoria de los números de la lista
#inicializo la variable de sumatoria
sum=0
for i in lista:
  sum= i+ sum

print("Suma de los números de la lista: ", sum)
#D. Lista con los números menores al dado

nmayor= int(input("Ingrese un número para crear una lista con los números menores que este de la lista: "))

#Inicializo la lista con los números menores
menores= []
for i in lista:
  if i< nmayor:
    menores.append(i)

print("Lista con números menores al dado: ", menores)

# E. Generar e imprimir una nueva lista que contenga como elementos a tuplas de dos elementos, 
#cada una compuesta por un número de la lista original y la cantidad de veces que aparece en ella. 
#Por ejemplo, si la lista original es [5,16,2,5,57,5,2] la nueva lista contendrá: [(5,3), (16,1), (2,2), (57,1)]

lista_tuplas= []
for i in lista:
  if (i, lista.count(i)) not in lista_tuplas:
    lista_tuplas.append((i,lista.count(i)))

print("Lista de tuplas: ", lista_tuplas)


Ingrese un número para guardar en una lista, con 0 termina la lista (entero): 8
Ingrese un número para guardar en una lista, con 0 termina la lista (entero): 21
Ingrese un número para guardar en una lista, con 0 termina la lista (entero): 23
Ingrese un número para guardar en una lista, con 0 termina la lista (entero): 16
Ingrese un número para guardar en una lista, con 0 termina la lista (entero): 14
Ingrese un número para guardar en una lista, con 0 termina la lista (entero): 8
Ingrese un número para guardar en una lista, con 0 termina la lista (entero): 21
Ingrese un número para guardar en una lista, con 0 termina la lista (entero): 23
Ingrese un número para guardar en una lista, con 0 termina la lista (entero): 16
Ingrese un número para guardar en una lista, con 0 termina la lista (entero): 8
Ingrese un número para guardar en una lista, con 0 termina la lista (entero): 8
Ingrese un número para guardar en una lista, con 0 termina la lista (entero): 16
Ingrese un número para guardar e

In [ ]:
#Crear lista vacía
lista =list()

def sumatoria(lista):
    suma=0
    for n in lista:
        suma+=n
    return suma

 
def numerosMenores(lista, limite):
    nueva=[]
    for n in lista:
        if n<limite:
            nueva.append(n)
    return nueva

 
def frecuencias(lista):
    nueva=[]
    for n in lista:
        if [n, lista.count(n)] not in nueva:
            nueva.append([n, lista.count(n)])
    return nueva

 
#A
numeros=[]
nro=int(input("Número: "))
while nro!=0:
    numeros.append(nro)
    nro=int(input("Número: "))
#B
if eliminar in numeros:
    numeros.remove(eliminar)
else:
    print("Ese número no está entre los ingresados")

#C
print("Sumatoria de los números:", sumatoria(numeros))
eliminar=int(input("Número a eliminar: "))

#D
limite=int(input("Filtrar números menores a: "))
for n in numerosMenores(numeros, limite):
    print(n)
#E
print("Frecuencias:")
for tupla in frecuencias(numeros):
    print(tupla[0],"aparece",tupla[1],"veces.")

# **Numpy**
## Arrays

In [ ]:
import numpy as np

x = np.array([1,2,3,4,5])
x
print("Acceder al atributo tipo con Python (type(x)): " ,type(x), "Acceder a dimensión (x.ndim): ",x.ndim, 
      ", Tamaño total del array: ", x.shape, ", Tipo de sus elementos: ", x.dtype)

Acceder al atributo tipo con Python (type(x)):  <class 'numpy.ndarray'> Acceder a dimensión (x.ndim):  1 , Tamaño total del array:  (5,) , Tipo de sus elementos:  int64


## Matrices

In [ ]:
Matriz = np.array ([[1,2,3], [4,5,6], [7,8,9]])
Matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
Matriz.ndim #dimensión

2

In [ ]:
Matriz.size #Tamaño

9

In [ ]:
Matriz.shape #Número de filas y columnas

(3, 3)

In [ ]:
Matriz.dtype

dtype('int64')

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.diag((5,4,3,2,1))

array([[5, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1]])

## Valores aleatorios

In [ ]:
np.random.random(9)

array([0.85083823, 0.23123959, 0.43258002, 0.19606584, 0.052484  ,
       0.47248793, 0.42341613, 0.61730307, 0.81886531])

In [ ]:
np.random.uniform(1,100,size=9)

array([26.21792464, 16.94240287, 81.08857954, 91.28187976, 24.0177365 ,
       96.65102459, 86.30992125, 18.03137372, 77.4245355 ])

In [ ]:
np.random.normal(0,5, size= 1_000_00)

array([ 7.18139829, -4.4099146 , -9.86897333, ...,  1.79887058,
        8.9981177 ,  9.12462252])

In [ ]:
np.random.choice(["head", "tail", "hand"], size= 1_00)

array(['hand', 'tail', 'hand', 'tail', 'hand', 'tail', 'tail', 'head',
       'head', 'head', 'head', 'tail', 'head', 'head', 'head', 'tail',
       'hand', 'hand', 'tail', 'hand', 'head', 'tail', 'tail', 'tail',
       'tail', 'head', 'tail', 'hand', 'head', 'hand', 'tail', 'head',
       'head', 'hand', 'head', 'head', 'tail', 'hand', 'hand', 'hand',
       'hand', 'head', 'head', 'tail', 'head', 'head', 'head', 'head',
       'head', 'hand', 'hand', 'hand', 'hand', 'head', 'head', 'tail',
       'tail', 'head', 'tail', 'head', 'hand', 'head', 'hand', 'tail',
       'tail', 'tail', 'tail', 'hand', 'tail', 'head', 'tail', 'head',
       'tail', 'head', 'tail', 'head', 'tail', 'head', 'hand', 'hand',
       'head', 'tail', 'head', 'tail', 'tail', 'hand', 'head', 'hand',
       'tail', 'tail', 'tail', 'head', 'hand', 'hand', 'head', 'tail',
       'head', 'head', 'tail', 'head'], dtype='<U4')

# **Pandas**
## Series

In [ ]:
import pandas as pd
import numpy as np

items1= pd.Series([1,2,3], index= ["a", "b", "c"])
items1

a    1
b    2
c    3
dtype: int64

In [ ]:
items2= {"a": 1, "b": 2, "c": 3}
#Convierto al diccionario como una serie
items2=pd.Series(items2, name="Nombre")
items2

a    1
b    2
c    3
Name: Nombre, dtype: int64

In [ ]:
print("Tipo de la serie: ",items2.dtype)
print("Índice de la serie: ",items2.index)
print("Valores de la serie: ",items2.values)
print("Nombre de la serie: ",items2.name)
print("Memoria ocupada por la serie: ",items2.nbytes)
print("Número de registros de la serie ",items2.size)

Tipo de la serie:  int64
Índice de la serie:  Index(['a', 'b', 'c'], dtype='object')
Valores de la serie:  [1 2 3]
Nombre de la serie:  Nombre
Memoria ocupada por la serie:  24
Número de registros de la serie  3


## Dataframe

In [ ]:
datos = {"M": [1,2,3], "P": [4,5,6]}

pd.DataFrame(datos)

M  P
0  1  4
1  2  5
2  3  6

In [ ]:
# Celda de código para probar
#con diccionarios
import pandas as pd
import numpy as np
nombre_curso= ["Fundamentos de Estadística", "Programación", "Seminario"]
nombre_prof= ["Mariana", "Jorge Victorino", "Jorge Mejía"]
hora_inicio =[6, 6, 11]
dia_clase =["jueves", "viernes", "sábado"]
c_horas= [5, 4, 3]
semestre = [1, 1, 1]

horario = pd.DataFrame({"Nombre del curso": nombre_curso, "Nombre del profesor": nombre_prof, "Hora de inicio": hora_inicio,
                       "Dia": dia_clase, "No. Horas": c_horas, "Semestre": semestre})
horario

Nombre del curso Nombre del profesor  Hora de inicio      Dia  \
0  Fundamentos de Estadística             Mariana               6   jueves   
1                Programación     Jorge Victorino               6  viernes   
2                   Seminario         Jorge Mejía              11   sábado   

   No. Horas  Semestre  
0          5         1  
1          4         1  
2          3         1

In [ ]:
# Celda de código para probar
# Abrir los archivos
import pandas as pd
import numpy as np
# Función para abrir archivo
def recibe_fun (archivo):
  dfi=pd.read_csv(archivo, sep=',', encoding='utf-8', error_bad_lines=False)
  return dfi
  print(dfi.head(10))
recibe_fun("iris.csv")

In [ ]:
#Guardar el archivo csv en dfi
dfi=pd.read_csv("iris.csv", sep=',', encoding='utf-8', error_bad_lines=False)

#Hacer una lista con las columnas del archivo csv
nombre_col= list(dfi.columns)
#inicializo listas vacías
tipol= []
mxl=[]
mnl=[]
c_datosnul= []
lvalorunic= []
lv_frec= []
#Contador en 0
i=0
rango= dfi.index
c_datos=len(dfi)

tipoL= list(dfi.dtypes) 
mxL= list(dfi.max())
mnL= list(dfi.min())
no_nulos = list(c_datos-dfi.isnull().sum())
v_unico = list(dfi.groupby(nombre_col[0]).nunique().sum())
v_frecuente= list(dfi.mode())

#Con la función zip(), iteramos sobre las múltiples listas en paralelo
registro= list(zip(tipoL, mxL, mnL, no_nulos, v_unico, v_frecuente))
#print(registro)
dfidesc= pd.DataFrame(registro, columns= ['Tipo', 'Máximo', 'Mínimo', "Valores no nulos", "Valores únicos", "Valores frec"])
print(dfidesc)
dfi.describe()

      Tipo  Máximo  Mínimo  Valores no nulos  Valores únicos  Valores frec
0  float64     7.9     4.3               150             117  sepal.length
1  float64     4.4     2.0               150             123   sepal.width
2  float64     6.9     1.0               150             110  petal.length
3  float64     2.5     0.1               150              57   petal.width


/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)


sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000